### PR TITLE
Added Functionality to ConcreteOutputObserver

### PR DESCRIPTION
**Pull request by murphl3**
I added the functionality to ConcreteOutputObserver.

### CODE REVIEW

**Review by AdamShk123 — CHANGES_REQUESTED** [review]
you can change iterator line to `cloud.toSeq.sortBy(_._2)(Ordering[Int].reverse).iterator`. This should make it into only a single sorting operation.

Sorry about the test case, I could have made it easier, but I forgot about not leaving a space at the end of the string. You can change the test case to have a space at the end to make it easier and then simplify the while loop into something like this:
```
var output = ""
for(key <- keys)
  output += key._1 + ": " + key._2 + " "
```

Also, you're right that the sorting operation should probably be moved into the word cloud class. There is a mutable `SortedMap` type we could use and then pass that to the output observer. If you feel that's better, you can change the test case to use that instead and then modify the `convert` function accordingly.

**Comment by AdamShk123** [comment]
Actually, for now don't bother with the `SortedMap` and just put the sorting operation in the test case code, so that the `convert` function doesn't need to tackle that. Once Liam R. starts working on `WordCloud`, we can decide how we'll sort the contents of the map

**Review by karamkhan1 — COMMENTED** [review]
LGTM

**Review by AdamShk123 — APPROVED** [review]
LGTM

**Pull request merged**
